name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: community-gdvwebsite
  ACR_NAME: ${{ secrets.ACR_NAME }}
  LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure correct subscription
        run: az account set --subscription $AZURE_SUBSCRIPTION_ID

      - name: ACR login (AAD)
        run: az acr login --name $ACR_NAME

      - name: Build & Push (master tag only)
        run: |
          IMAGE=$LOGIN_SERVER/$IMAGE_NAME:master
          docker build -t $IMAGE -f gdv/Dockerfile gdv
          docker push $IMAGE
